package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", schema = "public")
public class Ciudad implements java.io.Serializable {

    private int idCiudad;
    private String descriCiudad;
    private List<Ciudad> ciudad = new ArrayList();

    public Ciudad() {
    }

    public Ciudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }

    public Ciudad(int idCiudad, String descriCiudad) {
        this.idCiudad = idCiudad;
        this.descriCiudad = descriCiudad;
    }

    @Id
    @GeneratedValue
    @Column(name = "id_ciudad", unique = true, nullable = false)
    public int getIdCiudad() {
        return this.idCiudad;
    }

    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }

    @Column(name = "descri_ciudad", length = 50)
    public String getDescriCiudad() {
        return this.descriCiudad;
    }

    public void setDescriCiudad(String descriCiudad) {
        this.descriCiudad = descriCiudad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ciudad")
    public List<Ciudad> getCiudad() {
        return ciudad;
    }

    public void setCiudad(List<Ciudad> pais) {
        this.ciudad = pais;
    }
}
