package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name="comentario"
    ,schema="public"
)
public class Comentario  implements java.io.Serializable {


     private int idCom;
     private Usuario usuario;
     private Libro libro;
     private Date fechaCom;
     private String comentario;

    public Comentario() {
    }

	
    public Comentario(int idCom) {
        this.idCom = idCom;
    }
    public Comentario(int idCom, Usuario usuario, Libro libro, Date fechaCom, String comentario) {
       this.idCom = idCom;
       this.usuario = usuario;
       this.libro = libro;
       this.fechaCom = fechaCom;
       this.comentario = comentario;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="id_com", unique=true, nullable=false)
    public int getIdCom() {
        return this.idCom;
    }
    
    public void setIdCom(int idCom) {
        this.idCom = idCom;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_libro")
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_com", length=13)
    public Date getFechaCom() {
        return this.fechaCom;
    }
    
    public void setFechaCom(Date fechaCom) {
        this.fechaCom = fechaCom;
    }

    
    @Column(name="comentario", length=1024)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


