package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContadorVisitas generated by hbm2java
 */
@Entity
@Table(name="contador_visitas"
    ,schema="public"
)
public class ContadorVisitas  implements java.io.Serializable {


     private int idCont;
     private Libro libro;
     private Integer cantidad;

    public ContadorVisitas() {
    }

	
    public ContadorVisitas(int idCont) {
        this.idCont = idCont;
    }
    public ContadorVisitas(int idCont, Libro libro, Integer cantidad) {
       this.idCont = idCont;
       this.libro = libro;
       this.cantidad = cantidad;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="id_cont", unique=true, nullable=false)
    public int getIdCont() {
        return this.idCont;
    }
    
    public void setIdCont(int idCont) {
        this.idCont = idCont;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_libro")
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


