package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleVenta generated by hbm2java
 */
@Entity
@Table(name="detalle_venta"
    ,schema="public"
)
public class DetalleVenta  implements java.io.Serializable {


     private int idDetVent;
     private VentaCab ventaCab;
     private Libro libro;
     private Integer cantVent;
     private Double importeVnt;

    public DetalleVenta() {
    }

	
    public DetalleVenta(int idDetVent) {
        this.idDetVent = idDetVent;
    }
    public DetalleVenta(int idDetVent, VentaCab ventaCab, Libro libro, Integer cantVent, Double importeVnt) {
       this.idDetVent = idDetVent;
       this.ventaCab = ventaCab;
       this.libro = libro;
       this.cantVent = cantVent;
       this.importeVnt = importeVnt;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="id_det_vent", unique=true, nullable=false)
    public int getIdDetVent() {
        return this.idDetVent;
    }
    
    public void setIdDetVent(int idDetVent) {
        this.idDetVent = idDetVent;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_venta")
    public VentaCab getVentaCab() {
        return this.ventaCab;
    }
    
    public void setVentaCab(VentaCab ventaCab) {
        this.ventaCab = ventaCab;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_libro")
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }

    
    @Column(name="cant_vent")
    public Integer getCantVent() {
        return this.cantVent;
    }
    
    public void setCantVent(Integer cantVent) {
        this.cantVent = cantVent;
    }

    
    @Column(name="importe_vnt", precision=17, scale=17)
    public Double getImporteVnt() {
        return this.importeVnt;
    }
    
    public void setImporteVnt(Double importeVnt) {
        this.importeVnt = importeVnt;
    }




}


