package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Editorial generated by hbm2java
 */
@Entity
@Table(name="editorial"
    ,schema="public"
)
public class Editorial  implements java.io.Serializable {


     private int idEditorial;
     private String descriEditorial;
     private List<Libro> libros = new ArrayList(0);

    public Editorial() {
    }

	
    public Editorial(int idEditorial) {
        this.idEditorial = idEditorial;
    }
    public Editorial(int idEditorial, String descriEditorial, List<Libro> libros) {
       this.idEditorial = idEditorial;
       this.descriEditorial = descriEditorial;
       this.libros = libros;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="id_editorial", unique=true, nullable=false)
    public int getIdEditorial() {
        return this.idEditorial;
    }
    
    public void setIdEditorial(int idEditorial) {
        this.idEditorial = idEditorial;
    }

    
    @Column(name="descri_editorial", length=1024)
    public String getDescriEditorial() {
        return this.descriEditorial;
    }
    
    public void setDescriEditorial(String descriEditorial) {
        this.descriEditorial = descriEditorial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="editorial")
    public List<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(List<Libro> libros) {
        this.libros = libros;
    }




}


