package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,schema="public"
)
public class Pais  implements java.io.Serializable {



     private int idPais;
     private Ciudad ciudad;
     private String descriPais;

    public Pais() {
    }


    public Pais(int idPais, String descriPais) {
        this.idPais = idPais;
        this.descriPais=descriPais;
    }

	
    public Pais(int idPais, String descriPais, Ciudad ciudad) {
        this.idPais = idPais;
        this.ciudad= ciudad;
        this.descriPais=descriPais;
    }
    
   
     @Id 

    @GeneratedValue
    @Column(name="id_pais", unique=true, nullable=false)
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ciudad")
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="descri_pais", length=50)
    public String getDescriPais() {
        return this.descriPais;
    }
    
    public void setDescriPais(String descriPais) {
        this.descriPais = descriPais;
    }

}


