package entidades;
// Generated 14/07/2014 03:02:32 AM by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VentaCab generated by hbm2java
 */
@Entity
@Table(name="venta_cab"
    ,schema="public"
)
public class VentaCab  implements java.io.Serializable {


     private int idVenta;
     private Usuario usuario;
     private Date fechaVenta;
     private Double totalVenta;
     private Boolean entregadoVenta;
     private List<DetalleVenta> detalleVentas = new ArrayList();

    public VentaCab() {
    }

	
    public VentaCab(int idVenta) {
        this.idVenta = idVenta;
    }
    public VentaCab(int idVenta, Usuario usuario, Date fechaVenta, Double totalVenta, Boolean entregadoVenta, List<DetalleVenta> detalleVentas) {
       this.idVenta = idVenta;
       this.usuario = usuario;
       this.fechaVenta = fechaVenta;
       this.totalVenta = totalVenta;
       this.entregadoVenta = entregadoVenta;
       this.detalleVentas = detalleVentas;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="id_venta", unique=true, nullable=false)
    public int getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(int idVenta) {
        this.idVenta = idVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario")
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_venta", length=13)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    
    @Column(name="total_venta", precision=17, scale=17)
    public Double getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(Double totalVenta) {
        this.totalVenta = totalVenta;
    }

    
    @Column(name="entregado_venta")
    public Boolean getEntregadoVenta() {
        return this.entregadoVenta;
    }
    
    public void setEntregadoVenta(Boolean entregadoVenta) {
        this.entregadoVenta = entregadoVenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ventaCab")
    public List<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(ArrayList detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


